### ISSUE TITLE
Suggestion: hooks to check that downstream files have also been updated

### ISSUE THREAD

**Issue by bfgray3** [lorenzwalthert/pre-commit-hooks#2]
I'd love to see some hooks here that check if certain files are newer than others, e.g. the hook created by [usethis::use_readme_rmd()](https://github.com/r-lib/usethis/blob/master/R/readme.R#L24) for checking if `README.Rmd` has been modified since `README.md` was last rendered.  Similarly, I think it might be helpful to have one that checks `data/*.rda` and `R/sysdata.rda` to see if any `data-raw/*.R` files have been modified more recently.  I think it can be easy to forget to regenerate these downstream files before committing.  Happy to help out if you think these would be useful.

**Comment by lorenzwalthert** [comment]
I agree. Interested in making a PR? I think also we need to think about how we can test these things. Even if it is writing down instructions for manual test.

**Comment by bfgray3** [comment]
I'd be happy to make a PR.  I could also make a PR with some tests written in Bash if you think that would be helpful.

**Comment by lorenzwalthert** [comment]
Yes, I think it's would be good to have some tests just right from the beginning. How would you implement them? They should run on all major platforms. One way would be to use a git interface from a language like python or R because that would make testing / try except ect. easier. Or simply use a a package like processx or the `system` command or a package like `git2r` but I think the last one might be an overkill. I imagine the tests to run as follows on a CI service:

- adding a folder ` test` to this repo with a script `execute-test.R/py`   that contains code to execute for the tests.
- clone this repo. 
- create a new folder ` tests/exec` or similar.
- run ` tests/execute-test.R/py`. 

The structure of the tests would be: 

- create a new file.
- execute ` $ git add && git commit -m "..."` and either expect exit status 0 or 1 (we should test for errors too)

What do you think? If we use a package like [`tic`](https://github.com/ropenscilabs/tic), we could set this up for CI agnostic for appveyor and travis.

**Comment by bfgray3** [comment]
I think it would be nice to use an R/Python Git interface for these tests.

**Comment by lorenzwalthert** [comment]
Let's continue discussion for tests in a separate issue (#4).

**Comment by lorenzwalthert** [comment]
Closed somewhere somehow :-)

**Comment by lorenzwalthert** [comment]
Or do you want to come up with a hook for `data/*.rds`?

**Comment by bfgray3** [comment]
Thanks!  I've been away from open source for a while but I appreciate your help.
